image: maven:3.8-openjdk-11

stages:
  - build
  - test
  
build_job:
  
  stage: build

  script:
    - mvn compile
    
test_job:
  stage: test
  script:
    - mvn clean verify -Dtest="APIRunner"
  

